src/FoodCompare.Web/Controllers/DatabaseController.cs
using FoodCompare.Web.Data;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FoodCompare.Web.Controllers
{
    public class DatabaseController : BaseController
    {
        public DatabaseController()
        { 
        }

        public DatabaseController(IDbConnection db) : base(db) { }

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Clear()
        {
            Database.Create();
            return RedirectToAction("Index");
        }
    }
}

src/FoodCompare.Web/Controllers/ExportController.cs
using CsvHelper;
using FoodCompare.Web.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiceStack.OrmLite;

namespace FoodCompare.Web.Controllers
{
    public class ExportController : BaseController
    {
        private readonly IDbConnection _db;

        public ExportController(IDbConnection db) : base(db)
        {
            _db = db;
        }

        public ActionResult Tags(bool text = false)
        {
            Export<Tag>(text);
            return new EmptyResult();
        }

        public ActionResult Foods(bool text = false)
        {
            Export<Food>(text);
            return new EmptyResult();
        }

        public ActionResult Scraps(bool text = false)
        {
            Export<Scrap>(text);
            return new EmptyResult();
        }

        private void Export<T>(bool text) where T: class
        {
            new DbCsvExporter(_db).Write<T>(new StreamWriter(Response.OutputStream));

            if (text)
            {
                Response.ContentType = "text/plain";
            }
            else
            {
                Response.ContentType = "text/csv";
                string fileName = typeof(T).Name.ToLower();
                Response.AddHeader("Content-Disposition", String.Format("attachment;filename={0}.csv", fileName));
            }
        }
    }

    public class DbCsvExporter
    {
        private readonly IDbConnection _db;

        public DbCsvExporter(IDbConnection db)
        {
            _db = db;
        }

        public void Write<T>(TextWriter writer) where T : class
        {
            var table = _db.Select<T>();
            using (var csv = new CsvWriter(writer))
            {
                csv.WriteRecords(table);
            }
        }
    }
}

src/FoodCompare.Web/Controllers/ImportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using CsvHelper;
using ServiceStack.OrmLite;
using FoodCompare.Web.Models;

namespace FoodCompare.Web.Controllers
{
    public class ImportController : BaseController
    {
        private readonly IDbConnection _db;

        public ImportController(IDbConnection db) : base(db)
        {
            _db = db;
        }

        public ActionResult Tags(HttpPostedFileBase file)
        {
            Import<Tag>(file);
            return RedirectToAction("Index", "Tags");
        }

        public ActionResult Foods(HttpPostedFileBase file)
        {
            Import<Food>(file);
            return RedirectToAction("Index", "Foods");
        }

        public ActionResult Scraps(HttpPostedFileBase file)
        {
            Import<Scrap>(file);
            return RedirectToAction("Index", "Scraps");
        }

        private void Import<T>(HttpPostedFileBase file) where T : class, new()
        {
            using (var reader = new StreamReader(file.InputStream))
            {
                new DbCsvImporter(_db).Read<T>(reader);
            }
        }
    }

    public class DbCsvImporter
    {
        private readonly IDbConnection _db;

        public DbCsvImporter(IDbConnection db)
        {
            _db = db;
        }

        public void Read<T>(TextReader reader) where T : class, new()
        {
            using (var csv = new CsvReader(reader))
            {
                var records = csv.GetRecords<T>().ToList();
                _db.InsertAll<T>(records);
            }
        }
    }
}

src/FoodCompare.Web/Views/Database/Index.cshtml
<h2>Database Utils</h2>

<h3>Export</h3>

@using (Html.BeginForm("Tags", "Export")) {
  <button class="btn">Export <strong>Tags</strong></button>
}

@using (Html.BeginForm("Foods", "Export")) {
  <button class="btn">Export <strong>Foods</strong></button>
}

@using (Html.BeginForm("Scraps", "Export")) {
  <button class="btn">Export <strong>Scraps</strong></button>
}

<h3>Import</h3>

@using (Html.BeginForm("Tags", "Import", method: FormMethod.Post, htmlAttributes: new { enctype = "multipart/form-data" })) {
  <label for="TagsFile">Tags</label>
  <button id="TagsFile" class="btn file-button">Choose File</button>
  <input class="hide" name="file" type="file"/>
  <button class="btn file-submit" disabled="disabled">Import <strong></strong></button>
}

@using (Html.BeginForm("Foods", "Import", method: FormMethod.Post, htmlAttributes: new { enctype = "multipart/form-data" })) {
  <label for="PostsFile">Foods</label>
  <button id="PostsFile" class="btn file-button">Choose File</button>
  <input class="hide" name="file" type="file"/>
  <button class="btn file-submit" disabled="disabled">Import <strong></strong></button>
}

@using (Html.BeginForm("Scraps", "Import", method: FormMethod.Post, htmlAttributes: new { enctype = "multipart/form-data" })) {
  <label for="ScrapsFile">Scraps</label>
  <button id="ScrapsFile" class="btn file-button">Choose File</button>
  <input class="hide" name="file" type="file"/>
  <button class="btn file-submit" disabled="disabled">Import <strong></strong></button>
}

<h3>Clear Database</h3>

@using (Html.BeginForm("Clear", "Database")) {
  <button class="btn">Clear Database</button>
}

@section script {
<script>
  $('.file-button').on('click', function(e) {
    e.preventDefault();
    $(this).siblings('input[type=file]').trigger('click');
  });

  $('input[type=file]').change(function() {
    $(this).siblings('.file-submit')
      .prop('disabled', false)
      .find('strong').text(this.files[0].name);
  });
</script>
}