src/FoodCompare.Web/Controllers/TaggedController.cs
using FoodCompare.Web.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiceStack.OrmLite;

namespace FoodCompare.Web.Controllers
{
    public class TaggedController : BaseController
    {
        private readonly IDbConnection _db;

        public TaggedController(IDbConnection db) : base(db)
        {
            _db = db;
        }

        public ActionResult Index(string name)
        {
            var tag = _db.First<Tag>(p => p.Name == name);
            var foods = _db.Select<Food>(p => p.Tags.Contains(name));
            return View(new TaggedFoodViewModel
            {
                Tag = tag,
                Foods = foods,
                Totals = new Food
                {
                    Product = "Total",
                    Calories = foods.Sum(f => f.Calories),
                    Carbohydrate = foods.Sum(f => f.Carbohydrate),
                    Protein = foods.Sum(f => f.Protein),
                    Fat = foods.Sum(f => f.Fat),
                    Price = foods.Sum(f => f.Price)
                }
            });
        }
    }
}

src/FoodCompare.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Food Compare</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="~/assets/lib/bootstrap/css/bootstrap.css" rel="stylesheet" media="screen">
</head>
<body>
<div class="container-fluid">
    <h1>Food Compare</h1>

    <div class="row-fluid">
      <div class="span2">
          @{Html.RenderPartial("_Nav");}
      </div>
      <div id="content" class="span10">
          @RenderBody()
      </div>
    </div>
</div>
<script src="~/assets/lib/jquery-2.0.0/index.js"></script>
<script src="~/assets/lib/bootstrap/js/bootstrap.js"></script>
@RenderSection("script", required: false)
</body>
</html>

src/FoodCompare.Web/Views/Shared/_Nav.cshtml
<ul class="nav nav-list">
  <li class="nav-header">Tags</li>
  @if (ViewBag.Tags != null) {
    foreach (var tag in (List<FoodCompare.Web.Models.Tag>) ViewBag.Tags) {
      <li>@Html.ActionLink(tag.Name, "Index", "Tagged", new {Name = tag.Name}, null)</li>
    }
  }

  <!-- Admin/editing -->
  <li class="nav-header">Admin</li>
  <li>@Html.ActionLink("Tags", "Index", "Tags")</li>
  <li>@Html.ActionLink("Foods", "Index", "Foods")</li>
  <li>@Html.ActionLink("Scraps", "Index", "Scraps")</li>
  <li>@Html.ActionLink("Database", "Index", "Database")</li>
</ul>