src/FoodCompare.Web/Models/Scrap.cs
using ServiceStack.DataAnnotations;

namespace FoodCompare.Web.Models
{
    public class Scrap
    {
        [AutoIncrement]
        public int Id { get; set; }

        [References(typeof(Food))]
        public int? FoodId { get; set; }
        public string Url { get; set; }
        public string BrandXPath { get; set; }
        public string ProductXPath { get; set; }
        public string CaloriesXPath { get; set; }
        public string CarbohydrateXPath { get; set; }
        public string ProteinXPath { get; set; }
        public string FatXPath { get; set; }

        public Food Preview { get; set; }
    }
}

src/FoodCompare.Web/Controllers/FoodsController.cs
using FoodCompare.Web.Models;
using FoodCompare.Web.Data;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiceStack.OrmLite;
using ServiceStack.OrmLite.SqlServer;

namespace FoodCompare.Web.Controllers
{
    public class FoodsController : BaseController
    {
        private readonly IDbConnection db;

        public FoodsController()
        {
            
        }

        public FoodsController(IDbConnection db) : base(db)
        {
            this.db = db;
        }

        public ActionResult Index()
        {
            return View(db.Select<Food>());
        }

        public ActionResult Add()
        {
            return View();
        }

        public ActionResult AddFromScrap(int id)
        {
            var food = db.GetById<Scrap>(id).Preview;
            return View("Add", food);
        }

        [HttpPost]
        public ActionResult Add(Food request)
        {
            db.Insert(request);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            return View(db.GetById<Food>(id));
        }

        [HttpPost]
        public ActionResult Edit(Food request)
        {
            db.Update(request);
            return View(request);
        }

        public ActionResult Delete(int id)
        {
            return View(db.GetById<Food>(id));
        }

        [HttpPost]
        public ActionResult Delete(Food request)
        {
            db.Delete<Food>(f => f.Id == request.Id);
            return RedirectToAction("Index");
        }
    }
}

src/FoodCompare.Web/Controllers/ScrapsController.cs
using FoodCompare.Web.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiceStack.OrmLite;
using System.Text;
using HtmlAgilityPack;
using System.Text.RegularExpressions;
using System.Net;

namespace FoodCompare.Web.Controllers
{
    public class ScrapsController : BaseController
    {
        private readonly IDbConnection _db;

        public ScrapsController(IDbConnection db) : base(db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            return View(_db.Select<Scrap>());
        }

        public ActionResult Add()
        {
            return View(new Scrap());
        }

        public ActionResult AddFromScrap(int id)
        {
            var scrap = _db.GetById<Scrap>(id);
            scrap.Url = String.Empty;
            return View("Add", scrap);
        }

        [HttpPost]
        public ActionResult Add(Scrap scrap)
        {
            _db.Insert(scrap);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            return View(_db.GetById<Scrap>(id));
        }

        [HttpPost]
        public ActionResult Edit(Scrap scrap)
        {
            _db.Update(scrap);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            return View(_db.GetById<Scrap>(id));
        }

        [HttpPost]
        public ActionResult Delete(Scrap scrap)
        {
            _db.DeleteById<Scrap>(scrap.Id);
            return RedirectToAction("Index");
        }

        public ActionResult Run(int id)
        {
            var scrap = _db.GetById<Scrap>(id);
            ViewBag.Errors = String.Empty;
            ScrappedContent scrappedContent = new ScrappedContent();

            try
            {
                string content = String.Empty;
                using (var client = new WebClient())
                {
                    content = client.DownloadString(scrap.Url);
                }

                var scrapper = new XPathScrapper();
                scrappedContent = scrapper.Scrap(scrap, content);
            }
            catch (Exception ex)
            {
                ViewBag.Errors = ex.ToString();
            }

            ViewBag.Id = scrap.Id;
            scrap.Preview = scrappedContent.Food;
            _db.Update(scrap);
            return View(scrappedContent);
        }
    }

    public class ScrappedContent
    {
        public string Messages { get; set; }
        public Food Food { get; set; }
    }

    public class XPathScrapper
    {
        private StringBuilder _log = new StringBuilder();

        public ScrappedContent Scrap(Scrap scrap, string content)
        {
            var doc = new HtmlDocument();
            doc.LoadHtml(content);

            var food = new Food();

            if (!String.IsNullOrEmpty(scrap.BrandXPath))
            {
                Log("Brand");
                food.Brand = GetString(doc, scrap.BrandXPath);
            }

            if (!String.IsNullOrEmpty(scrap.ProductXPath))
            {
                Log("Product");
                food.Product = GetString(doc, scrap.ProductXPath);
            }

            if (!String.IsNullOrEmpty(scrap.CaloriesXPath))
            {
                Log("Calories");
                food.Calories = GetDecimal(doc, scrap.CaloriesXPath);
            }

            if (!String.IsNullOrEmpty(scrap.CarbohydrateXPath))
            {
                Log("Carbohydrate");
                food.Carbohydrate = GetDecimal(doc, scrap.CarbohydrateXPath);
            }

            if (!String.IsNullOrEmpty(scrap.ProteinXPath))
            {
                Log("Protein");
                food.Protein = GetDecimal(doc, scrap.ProteinXPath);
            }

            if (!String.IsNullOrEmpty(scrap.FatXPath))
            {
                Log("Fat");
                food.Fat = GetDecimal(doc, scrap.FatXPath);
            }

            return new ScrappedContent
            {
                Food = food,
                Messages = _log.ToString()
            };
        }

        private string GetString(HtmlDocument doc, string xpath)
        {
            var node = doc.DocumentNode.SelectSingleNode(xpath);
            if (node == null)
            {
                Log("Could not find node with XPath: {0}", xpath);
                return String.Empty;
            }

            string text = node.InnerText;
            if (String.IsNullOrWhiteSpace(text))
            {
                Log("No text found with XPath: {0}", xpath);
                return String.Empty;
            }

            Log("Result: {0}", text);
            return text;
        }

        private decimal GetDecimal(HtmlDocument doc, string xpath)
        {
            var node = doc.DocumentNode.SelectSingleNode(xpath);
            if (node == null)
            {
                Log("Could not find node with XPath: {0}", xpath);
                return 0M;
            }

            string text = node.InnerText;
            if (String.IsNullOrWhiteSpace(text))
            {
                Log("No text found with XPath: {0}", xpath);
                return 0M;
            }

            Log("Parsing text: {0}", text);
            text = text.ToLower();
            decimal value = 0M;
            string originalText = text;

            // Remove any non digit characters
            text = Regex.Replace(text, "[^0-9.]", String.Empty);

            // Convert to decimal
            if (!Decimal.TryParse(text, out value))
            {
                Log("Could not parse {0} into a decimal", text);
            }

            // KJ => Calories
            if (originalText.Contains("kj"))
            {
                Log("Detected kilo joules, converting to calories");
                value = Math.Round(value / 4.2M, 0);
            }

            // <1.0 => 0
            if (originalText.Contains("&lt;"))
            {
                Log("Converting <1.0 to 0");
                value = 0M;
            }

            Log("Result: {0}", value);
            return value;
        }

        private void Log(string message)
        {
            _log.AppendLine(message);
        }

        private void Log(string message, params object[] args)
        {
            _log.AppendFormat(message, args).AppendLine(); ;
        }
    }
}

src/FoodCompare.Web/Views/Scraps/Add.cshtml
@model FoodCompare.Web.Models.Scrap

<h2>Add Food Scrap</h2>
@using(Html.BeginForm("Add", "Scraps")) {
  <fieldset>
    <label>Food</label>
    @Html.LabelFor(m => m.Url)
    @Html.TextBoxFor(m => m.Url, htmlAttributes: new { @class = "input-xlarge" })
    @Html.LabelFor(m => m.BrandXPath)
    @Html.TextBoxFor(m => m.BrandXPath)
    @Html.LabelFor(m => m.ProductXPath)
    @Html.TextBoxFor(m => m.ProductXPath)
    @Html.LabelFor(m => m.CaloriesXPath)
    @Html.TextBoxFor(m => m.CaloriesXPath)
    @Html.LabelFor(m => m.CarbohydrateXPath)
    @Html.TextBoxFor(m => m.CarbohydrateXPath)
    @Html.LabelFor(m => m.ProteinXPath)
    @Html.TextBoxFor(m => m.ProteinXPath)
    @Html.LabelFor(m => m.FatXPath)
    @Html.TextBoxFor(m => m.FatXPath)
  </fieldset>
  <button type="submit" class="btn btn-primary">Add</button>
}

src/FoodCompare.Web/Views/Scraps/Delete.cshtml
@model FoodCompare.Web.Models.Scrap

<h2>Delete Scrap</h2>

@using (Html.BeginForm("Delete", "Scraps")) {
  @Html.HiddenFor(m => m.Id)
  <button class="btn">Delete <strong>@Model.Url</strong></button> 
}

src/FoodCompare.Web/Views/Scraps/Edit.cshtml
@model FoodCompare.Web.Models.Scrap

<h2>Add Food Scrap</h2>
@using(Html.BeginForm("Edit", "Scraps")) {
  <fieldset>
    <label>Food</label>
    @Html.LabelFor(m => m.Url)
    @Html.TextBoxFor(m => m.Url, htmlAttributes: new { @class = "input-xlarge" })
    @Html.LabelFor(m => m.BrandXPath)
    @Html.TextBoxFor(m => m.BrandXPath)
    @Html.LabelFor(m => m.ProductXPath)
    @Html.TextBoxFor(m => m.ProductXPath)
    @Html.LabelFor(m => m.CaloriesXPath)
    @Html.TextBoxFor(m => m.CaloriesXPath)
    @Html.LabelFor(m => m.CarbohydrateXPath)
    @Html.TextBoxFor(m => m.CarbohydrateXPath)
    @Html.LabelFor(m => m.ProteinXPath)
    @Html.TextBoxFor(m => m.ProteinXPath)
    @Html.LabelFor(m => m.FatXPath)
    @Html.TextBoxFor(m => m.FatXPath)
  </fieldset>
  <button type="submit" class="btn btn-primary">Edit</button>
}

src/FoodCompare.Web/Views/Scraps/Index.cshtml
@model List<FoodCompare.Web.Models.Scrap>

<h2 class="pull-left">Food Scraps</h2>
@Html.ActionLink("Add", "Add", "Scraps", routeValues: null, htmlAttributes: new { @class = "pull-right btn" })

<table class="table table-striped">
<thead>
  <tr>
    <th>Id</th>
    <th>Food Id</th>
    <th>Url</th>
    <th>Actions</th>
  </tr>
</thead>
<tbody>
  @foreach (var scrap in Model) {
  <tr>
    <td>@scrap.Id</td>
    <td>@scrap.FoodId</td>
    <td>@scrap.Url</td>
    <td>
      @Html.ActionLink("Run", "Run", "Scraps", routeValues: new { scrap.Id }, htmlAttributes: new { @class = "btn" })
      @Html.ActionLink("Edit", "Edit", "Scraps", routeValues: new { scrap.Id }, htmlAttributes: new { @class = "btn" })
      @Html.ActionLink("Create New", "AddFromScrap", "Scraps", routeValues: new { scrap.Id }, htmlAttributes: new { @class = "btn" })
      @Html.ActionLink("Delete", "Delete", "Scraps", routeValues: new { scrap.Id }, htmlAttributes: new { @class = "btn" })
    </td>
  </tr>}
</tbody>
</table>

src/FoodCompare.Web/Views/Scraps/Run.cshtml
@model FoodCompare.Web.Controllers.ScrappedContent
@{
    var errors = ViewBag.Errors as String;
    var id = (int)ViewBag.Id;
}

<h2>Scrap Run</h2>

@if (!String.IsNullOrEmpty(errors)) {
  <h3>Errors</h3>
  <pre>@errors</pre>
}

@if (Model.Food != null) {
  <h3>Preview</h3>
  <pre>@Model.Food.Dump()</pre>

  @Html.ActionLink("Create Food", "AddFromScrap", "Foods", new { id }, new { @class = "btn btn-primary" })
}

@if (!String.IsNullOrEmpty(Model.Messages)) {
  <h3>Messages</h3>
  <pre>@Model.Messages</pre>
}