src/FoodCompare.Web/Models/Tag.cs
using ServiceStack.DataAnnotations;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace FoodCompare.Web.Models
{
    public class Tag
    {
        [AutoIncrement]
        public int Id { get; set; }
        public string Name { get; set; }

        [DisplayName("Show Total")]
        public bool ShowTotal { get; set; }
    }
}

src/FoodCompare.Web/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiceStack.OrmLite;
using ServiceStack.OrmLite.SqlServer;
using FoodCompare.Web.Models;

namespace FoodCompare.Web.Controllers
{
    public class TagsController : BaseController
    {
        private readonly IDbConnection _db;

        public TagsController()
        {
        }

        public TagsController(IDbConnection db) : base(db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            return View(_db.Select<Tag>());
        }

        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Tag request)
        {
            _db.Insert(request);
            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            return View(_db.GetById<Tag>(id));
        }

        [HttpPost]
        public ActionResult Edit(Tag tag)
        {
            _db.Update(tag);
            return View(tag);
        }

        public ActionResult Delete(int id)
        {
            return View(_db.GetById<Tag>(id));
        }

        [HttpPost]
        public ActionResult Delete(Tag request)
        {
            _db.Delete<Tag>(request);
            return RedirectToAction("Index");
        }
    }
}

src/FoodCompare.Web/Views/Tags/Add.cshtml
@model FoodCompare.Web.Models.Tag

<h2>Add Tag</h2>

@using (Html.BeginForm("Add", "Tags")) {
  <fieldset>
    <legend></legend>
    @Html.LabelFor(m => m.Name)
    @Html.EditorFor(m => m.Name)
    <label class="checkbox">
      @Html.EditorFor(m => m.ShowTotal)
      @Html.DisplayNameFor(m => m.ShowTotal)
    </label>
  </fieldset>
  <button type="submit" class="btn btn-primary">Add Tag</button>
}

src/FoodCompare.Web/Views/Tags/Delete.cshtml
@model FoodCompare.Web.Models.Tag

<h2>Delete Tag</h2>

@using (Html.BeginForm("Delete", "Tags")) {
    <button class="btn"><strong>Delete</strong> @Model.Name</button>
}

src/FoodCompare.Web/Views/Tags/Edit.cshtml
@model FoodCompare.Web.Models.Tag

<h2>Edit Tag</h2>

@using (Html.BeginForm("Edit", "Tags")) {
  <fieldset>
    <legend></legend>
    @Html.LabelFor(m => m.Name)
    @Html.EditorFor(m => m.Name)
    <label class="checkbox">
      @Html.EditorFor(m => m.ShowTotal)
      @Html.DisplayNameFor(m => m.ShowTotal)
    </label>
  </fieldset>
  <button type="submit" class="btn btn-primary">Edit Tag</button>
}

src/FoodCompare.Web/Views/Tags/Index.cshtml
@model List<FoodCompare.Web.Models.Tag>

<h2 class="pull-left">Tags</h2>
@Html.ActionLink("Add", "Add", "Tags", routeValues: null, htmlAttributes: new { @class ="btn pull-right" })

<table class="table table-striped">
<thead>
  <tr>
    <th>Tag</th>
    <th>Actions</th>
  </tr>
</thead>
<tbody>
  @foreach (var tag in Model) {
  <tr>
    <td>@tag.Name</td>
    <td>
      @Html.ActionLink("Edit", "Edit", "Tags", routeValues: new { tag.Id }, htmlAttributes: new { @class = "btn" })
      @Html.ActionLink("Delete", "Delete", "Tags", routeValues: new { tag.Id } , htmlAttributes: new { @class = "btn" })
    </td>
  </tr>
  }
</tbody>
</table>